# Generated by Django 3.2 on 2022-05-30 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='saved_todo_user',
            field=models.ManyToManyField(blank=True, related_name='my_saved_todo', to=settings.AUTH_USER_MODEL),
        ),
    ]
